# fly.toml app configuration file generated for design-portfolio on 2025-04-01T00:04:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'design-portfolio'
primary_region = 'lhr'

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"